[package]
name = "game-of-life"
edition = "2024"

[dependencies]
multi-agent.workspace = true
# Graphical User Interface Dependencies
eframe.workspace = true
egui.workspace = true

[lints]
workspace = true
