[package]
name = "game-of-life"
edition = "2024"

[dependencies]
multi-agent.workspace = true
# Parallelization
rayon = { version = "1.11.0", features = [] }
# Graphical User Interface Dependencies
eframe.workspace = true
egui.workspace = true

[lints]
workspace = true
