[package]
name = "boids"
edition = "2024"

[dependencies]
multi-agent.workspace = true
fastrand = "2.3"
# Graphical User Interface Dependencies
eframe.workspace = true
egui.workspace = true

[lints]
workspace = true
